### ISSUE TITLE
Loading a model trained on a GPU machine fails on a CPU only machine

### ISSUE THREAD

**Issue by skumarlabs** [ourownstory/neural_prophet#1406]
**Prerequisites**

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in a new virtualenv with only neuralprophet installed, directly from github:
      ```shell
      git clone <copied link from github>
      cd neural_prophet
      pip install .
      ```
    * Checked the Answered Questions on the Github Disscussion board: https://github.com/ourownstory/neural_prophet/discussions
      If you have the same question but the Answer does not solve your issue, please continue the conversation there.
    * Checked that your issue isn't already filed: https://github.com/ourownstory/neural_prophet/issues
      If you have the same issue but there is a twist to your situation, please add an explanation there.
    * Considered whether your bug might actually be solveable by getting a question answered: 
      * Please [post a package use question](https://github.com/ourownstory/neural_prophet/discussions/categories/q-a-get-help-using-neuralprophet)
      * Please [post a forecasting best practice question](https://github.com/ourownstory/neural_prophet/discussions/categories/q-a-forecasting-best-practices)
      * Please [post an idea or feedback](https://github.com/ourownstory/neural_prophet/discussions/categories/ideas-feedback)

**Describe the bug**

An AR model trained on a machine with GPU cannot be loaded on a CPU only machine for inference.

1. Train a model with `accelerator='gpu'` on a GPU machine
```
hyperparams = {
        "n_lags": 2,
        "n_forecasts": 1,
        "epochs": 5,
        "trend_global_local": "local",
        "season_global_local": "local"
}
set_random_seed(0)
m = NeuralProphet(**hyperparams, accelerator='gpu')
train_metrics = m.fit(df_train, early_stopping=True, checkpointing=True, freq="D", progress="bar")
```
3. Save that model with 
```
from neuralpeophet import util           
util.save('saved_model.np')
```
4. Now, switch to CPU only machine and try to load that saved model
```
from neuralpeophet import util
m = util.load('saved_model.np')
```

5. See error

```
RuntimeError                              Traceback (most recent call last)
Cell In[51], line 1
----> 1 model = load(os.path.join(model_dir, 'saved_model.np'))
      2 with open(os.path.join(model_dir, f'top_model.json')) as fp:

File ~/.conda/envs/cpu-env/lib/python3.9/site-packages/neuralprophet/utils.py:65, in load(path)
     46 def load(path: str):
     47     """retrieve a fitted model from a .np file that was saved by save.
     48 
     49     Parameters
   (...)
     63         >>> model = load("test_save_model.np")
     64     """
---> 65     m = torch.load(path)
     66     m.restore_trainer()
     67     return m

File ~/.conda/envs/cpu-env/lib/python3.9/site-packages/torch/serialization.py:789, in load(f, map_location, pickle_module, weights_only, **pickle_load_args)
    787             except RuntimeError as e:
    788                 raise pickle.UnpicklingError(UNSAFE_MESSAGE + str(e)) from None
--> 789         return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
    790 if weights_only:
    791     try:

File ~/.conda/envs/cpu-env/lib/python3.9/site-packages/torch/serialization.py:1131, in _load(zip_file, map_location, pickle_module, pickle_file, **pickle_load_args)
   1129 unpickler = UnpicklerWrapper(data_file, **pickle_load_args)
   1130 unpickler.persistent_load = persistent_load
-> 1131 result = unpickler.load()
   1133 torch._utils._validate_loaded_sparse_tensors()
   1135 return result

File ~/.conda/envs/cpu-env/lib/python3.9/pickle.py:1212, in _Unpickler.load(self)
   1210             raise EOFError
   1211         assert isinstance(key, bytes_types)
-> 1212         dispatch[key[0]](self)
   1213 except _Stop as stopinst:
   1214     return stopinst.value

File ~/.conda/envs/cpu-env/lib/python3.9/pickle.py:1253, in _Unpickler.load_binpersid(self)
   1251 def load_binpersid(self):
   1252     pid = self.stack.pop()
-> 1253     self.append(self.persistent_load(pid))

File ~/.conda/envs/cpu-env/lib/python3.9/site-packages/torch/serialization.py:1101, in _load.<locals>.persistent_load(saved_id)
   1099 if key not in loaded_storages:
   1100     nbytes = numel * torch._utils._element_size(dtype)
-> 1101     load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
   1103 return loaded_storages[key]

File ~/.conda/envs/cpu-env/lib/python3.9/site-packages/torch/serialization.py:1083, in _load.<locals>.load_tensor(dtype, numel, key, location)
   1079 storage = zip_file.get_storage_from_record(name, numel, torch.UntypedStorage).storage().untyped()
   1080 # TODO: Once we decide to break serialization FC, we can
   1081 # stop wrapping with TypedStorage
   1082 loaded_storages[key] = torch.storage.TypedStorage(
-> 1083     wrap_storage=restore_location(storage, location),
   1084     dtype=dtype)

File ~/.conda/envs/cpu-env/lib/python3.9/site-packages/torch/serialization.py:215, in default_restore_location(storage, location)
    213 def default_restore_location(storage, location):
    214     for _, _, fn in _package_registry:
--> 215         result = fn(storage, location)
    216         if result is not None:
    217             return result

File ~/.conda/envs/cpu-env/lib/python3.9/site-packages/torch/serialization.py:182, in _cuda_deserialize(obj, location)
    180 def _cuda_deserialize(obj, location):
    181     if location.startswith('cuda'):
--> 182         device = validate_cuda_device(location)
    183         if getattr(obj, "_torch_load_uninitialized", False):
    184             with torch.cuda.device(device):

File ~/.conda/envs/cpu-env/lib/python3.9/site-packages/torch/serialization.py:166, in validate_cuda_device(location)
    163 device = torch.cuda._utils._get_device_index(location, True)
    165 if not torch.cuda.is_available():
--> 166     raise RuntimeError('Attempting to deserialize object on a CUDA '
    167                        'device but torch.cuda.is_available() is False. '
    168                        'If you are running on a CPU-only machine, '
    169                        'please use torch.load with map_location=torch.device(\'cpu\') '
    170                        'to map your storages to the CPU.')
    171 device_count = torch.cuda.device_count()
    172 if device >= device_count:

RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
```

Training a model on a GPU device and deploying that to a CPU only machine for inferencing is a very common workflow. Ideally, the model should be loaded even if GPU is not available.

As suggested in the logs, the fix seems to be obvious. If the model is trained on a GPU and is loaded on a CPU machine, the `load()` method [here](https://github.com/ourownstory/neural_prophet/blob/d236471ed2142320c1642c6e348acf8a3c0373ef/neuralprophet/utils.py#L65) needs to load it as below:

`m = torch.load(path, map_location=torch.device('cpu'))`

**Environement:**

 - Python 3.9, in standalone conda env
 - neuralprophet==0.6.2 installed from PYPI with `pip install neuralprophet`
 - torch==1.13.1+cu117
 - nvidia-cudnn-cu11==8.6.0.163
 - NVidia Tesla V100 GPU

**Comment by leoniewgnr** [comment]
@skumarlabs, thanks so much for finding this! This is indeed a problem! Does it work with `torch.load(path, map_location=torch.device('cpu'))`

**Comment by skumarlabs** [comment]
Yes. It worked for me, at least. I was able to load the model and generate predictions.

**Comment by leoniewgnr** [comment]
great to hear that! I'm going to close the issue with that, thanks so much for finding out!
